version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: collab-code-ai-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: collab-code-ai-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/collab-code-ai?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  # WebSocket Server (Yjs)
  websocket:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: collab-code-ai-websocket
    restart: unless-stopped
    ports:
      - "1234:1234"
    command: ["node", "websocket-server.js"]
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: collab-code-ai-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - websocket

volumes:
  mongodb_data: 